# Generated by Django 5.1.4 on 2024-12-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_alter_contact_options_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='partner',
        ),
        migrations.AddField(
            model_name='partner',
            name='products',
            field=models.ManyToManyField(to='relations.product'),
        ),
    ]
