# Generated by Django 5.1.4 on 2024-12-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_remove_product_partner_partner_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relations.partner', verbose_name='Поставщик'),
        ),
    ]
