# Generated by Django 5.1.4 on 2024-12-20 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0005_partner_type_organization_alter_partner_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relations.contact'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relations.partner'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type_organization',
            field=models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'ИП')]),
        ),
    ]
