# Generated by Django 5.1.4 on 2024-12-21 11:34

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0007_alter_partner_contact_alter_partner_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Задолженность'),
        ),
    ]
