# Generated by Django 5.1.4 on 2024-12-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0009_alter_partner_debt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('name',), 'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations.contact', verbose_name='Контакты'),
        ),
    ]
