# Generated by Django 5.1.4 on 2024-12-23 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0011_alter_partner_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='relations.contact', verbose_name='Контакты'),
        ),
    ]
