# Generated by Django 5.1.4 on 2024-12-24 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0012_alter_partner_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type_organization',
            field=models.SmallIntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'ИП')], validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='Тип организации'),
        ),
    ]
